language: c++
os: osx
osx_image: xcode8.3
branches:
  only:
  - master
  - develop
notifications:
  slack:
    secure: sS8dV4uF0miMIUXolG9nmbyI0IO88+/gZaazlEkC+ZAm+K3lP4z7jHyfHEtWMF17kEnNUynYuwr39+6IqgE0uzgq7Ak+1aHQnLnmWKuceC4BuruuVp8NcMeFTndy/ZphtO3CJw7DPfBKHCpg7sfnxMONaeePumBxNhqw0BNSW6c=
install: "./configure.sh"
env:
- BUILDTOOL=bjam BUILDMODE=debug
- BUILDTOOL=bjam BUILDMODE=release
- BUILDTOOL=xcode BUILDMODE=debug
- BUILDTOOL=xcode BUILDMODE=release
script: "./smoke_test.sh"
